apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
spec:
  template:
    spec:
      containers:
      - name: sealed-secrets-controller
        command:
        - controller
        - --key-renew-period=0
