name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build k3os
        run: |
          make
          du -sh dist/artifacts/k3os-amd64.iso
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: k3os-build
          path: dist

  release:
    runs-on: ubuntu-latest
    container: amazon/aws-cli
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: k3os-build
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Upload ISO to Wasabi
        run: |
          aws s3 cp --endpoint-url https://s3.eu-central-1.wasabisys.com k3os-build/artifacts/k3os-amd64.iso s3://hcloud-k3os/k3os-${{ steps.get_version.outputs.version }}-amd64.iso
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
